# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20100121012615) do

  create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.boolean  "email_private"
    t.integer  "stanford_class"
    t.string   "major"
    t.string   "degree"
    t.string   "company"
    t.string   "title"
    t.string   "job_start"
    t.string   "job_end"
    t.integer  "satisfaction"
    t.string   "six_words"
    t.text     "interview_text"
    t.datetime "interview_date"
    t.text     "summary"
    t.string   "keywords"
    t.integer  "author"
    t.integer  "total_views"
    t.integer  "total_authored"
    t.string   "image_file"
    t.integer  "views"
    t.integer  "likes"
    t.string   "new_question"
    t.string   "hashed_password"
    t.datetime "date_added"
    t.datetime "date_modified"
    t.string   "company1"
    t.string   "title1"
    t.integer  "job_start_m1"
    t.integer  "job_start_y1"
    t.integer  "job_end_m1"
    t.integer  "job_end_y1"
    t.integer  "satisfaction1"
    t.string   "responsibilities1"
    t.string   "company2"
    t.string   "title2"
    t.integer  "job_start_m2"
    t.integer  "job_start_y2"
    t.integer  "job_end_m2"
    t.integer  "job_end_y2"
    t.integer  "satisfaction2"
    t.string   "responsibilities2"
    t.string   "company3"
    t.string   "title3"
    t.integer  "job_start_m3"
    t.integer  "job_start_y3"
    t.integer  "job_end_m3"
    t.integer  "job_end_y3"
    t.integer  "satisfaction3"
    t.string   "responsibilities3"
    t.string   "company4"
    t.string   "title4"
    t.integer  "job_start_m4"
    t.integer  "job_start_y4"
    t.integer  "job_end_m4"
    t.integer  "job_end_y4"
    t.integer  "satisfaction4"
    t.string   "responsibilities4"
    t.string   "company5"
    t.string   "title5"
    t.integer  "job_start_m5"
    t.integer  "job_start_y5"
    t.integer  "job_end_m5"
    t.integer  "job_end_y5"
    t.integer  "satisfaction5"
    t.string   "responsibilities5"
    t.string   "company6"
    t.string   "title6"
    t.integer  "job_start_m6"
    t.integer  "job_start_y6"
    t.integer  "job_end_m6"
    t.integer  "job_end_y6"
    t.integer  "satisfaction6"
    t.string   "responsibilities6"
    t.string   "company7"
    t.string   "title7"
    t.integer  "job_start_m7"
    t.integer  "job_start_y7"
    t.integer  "job_end_m7"
    t.integer  "job_end_y7"
    t.integer  "satisfaction7"
    t.string   "responsibilities7"
    t.string   "company8"
    t.string   "title8"
    t.integer  "job_start_m8"
    t.integer  "job_start_y8"
    t.integer  "job_end_m8"
    t.integer  "job_end_y8"
    t.integer  "jobs_visible"
    t.integer  "satisfaction8"
    t.string   "responsibilities8"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
