# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20100121012615) do

  create_table "users", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.boolean  "email_private"
    t.integer  "stanford_class"
    t.string   "major"
    t.string   "degree"
    t.string   "company"
    t.string   "title"
    t.string   "job_start"
    t.string   "job_end"
    t.integer  "satisfaction"
    t.string   "six_words"
    t.text     "interview_text"
    t.datetime "interview_date"
    t.string   "summary"
    t.string   "keywords"
    t.integer  "author"
    t.integer  "total_views"
    t.integer  "total_authored"
    t.string   "image_file"
    t.integer  "views"
    t.integer  "likes"
    t.string   "new_question"
    t.string   "hashed_password"
    t.datetime "date_added"
    t.datetime "date_modified"
    t.string   "company1"
    t.string   "title1"
    t.string   "job_start1"
    t.string   "job_end1"
    t.integer  "satisfaction1"
    t.integer  "responsibilities1"
    t.string   "company2"
    t.string   "title2"
    t.string   "job_start2"
    t.string   "job_end2"
    t.integer  "satisfaction2"
    t.integer  "responsibilities2"
    t.string   "company3"
    t.string   "title3"
    t.string   "job_start3"
    t.string   "job_end3"
    t.integer  "satisfaction3"
    t.integer  "responsibilities3"
    t.string   "company4"
    t.string   "title4"
    t.string   "job_start4"
    t.string   "job_end4"
    t.integer  "satisfaction4"
    t.integer  "responsibilities4"
    t.string   "company5"
    t.string   "title5"
    t.string   "job_start5"
    t.string   "job_end5"
    t.integer  "satisfaction5"
    t.integer  "responsibilities5"
    t.string   "company6"
    t.string   "title6"
    t.string   "job_start6"
    t.string   "job_end6"
    t.integer  "satisfaction6"
    t.integer  "responsibilities6"
    t.string   "company7"
    t.string   "title7"
    t.string   "job_start7"
    t.string   "job_end7"
    t.integer  "satisfaction7"
    t.integer  "responsibilities7"
    t.string   "company8"
    t.string   "title8"
    t.string   "job_start8"
    t.string   "job_end8"
    t.integer  "satisfaction8"
    t.integer  "responsibilities8"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
